spring:
  application:
    name: SaasProject
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      data-source-properties:
        stringtype=unspecified
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework: INFO